on: [push]

jobs:
  test_action:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04, macos-latest, windows-latest, windows-2019]
    name: Install the cli
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install CLI
        uses: ./
        id: install
      - name: Test CLI
        run: doppler --version
